BEGIN
for i in (select * from tabs) loop
execute immediate ('drop table ' || i.table_name || ' cascade constraints');
end loop;
end;
/

CREATE TABLE STUDENT(
	STUDENT_ID INTEGER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	YEAR INTEGER(2),
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) INTEGER(10);
);


CREATE TABLE SUBJECT(
	SUBJECT_ID INTEGER(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20),
	DESCRIPTION VARCHAR(255),
	SEMESTER INTEGER(2);
);


CREATE TABLE COURSEWORK(
	COURSEWORK_ID INTEGER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) INTEGER(10),
	MAX_MARK INTEGER(10);
);


CREATE TABLE COURSEWORKRESULT(
	MARK_ACHIEVED INTEGER(10),
	STUDENT_ID FOREIGN KEY REFERENCES STUDENT(STUDENT_ID)) INTEGER(10),
	COURSEWORK_ID FOREIGN KEY REFERENCES COURSEWORK(COURSEWORK_ID) INTEGER(10);
);


CREATE TABLE EXAM(
	EXAM_ID INTEGER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TOTAL_MARK INTEGER(10),
	RESIT VARCHAR(3),
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) INTEGER(10);
);


CREATE TABLE EXAMRESULT(
	MARK_ACHIEVED INTEGER(10),
	STUDENT_ID FOREIGN KEY REFERENCES STUDENT(STUDENT_ID) INTEGER(10),
	EXAM_ID FOREIGN KEY REFERENCES EXAM(EXAM_ID) INTEGER(10);
);


CREATE TABLE LECTURER(
	LECTURER_ID INTEGER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) INTEGER(10);
);


CREATE TABLE QUESTION(
	QUESTION_ID INTEGER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MAX_MARK INTEGER(10),
	AUTHOR VARCHAR(50),
	EXAM_ID FOREIGN KEY REFERENCES EXAM(EXAM_ID) INTEGER(10),
	LECTURER_ID FOREIGN KEY REFERENCES LECTURER(LECTURER_ID) INTEGER(10);
);
