BEGIN
FOR c IN (SELECT table_name FROM user_tables) LOOP
EXECUTE IMMEDIATE ('DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS');
END LOOP;

echo "Dropped all tables currently present. Moving onto recreation.";

CREATE TABLE STUDENT(
	STUDENT_ID NUMBER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	YEAR NUMBER(2),
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) NUMBER(10);
);


CREATE TABLE SUBJECT(
	SUBJECT_ID NUMBER(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20),
	DESCRIPTION VARCHAR(255),
	SEMESTER NUMBER(2);
);


CREATE TABLE COURSEWORK(
	COURSEWORK_ID NUMBER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) NUMBER(10),
	MAX_MARK NUMBER(10);
);


CREATE TABLE COURSEWORKRESULT(
	MARK_ACHIEVED NUMBER(10),
	STUDENT_ID FOREIGN KEY REFERENCES STUDENT(STUDENT_ID)) NUMBER(10),
	COURSEWORK_ID FOREIGN KEY REFERENCES COURSEWORK(COURSEWORK_ID) NUMBER(10);
);


CREATE TABLE EXAM(
	EXAM_ID NUMBER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TOTAL_MARK NUMBER(10),
	RESIT VARCHAR(3),
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) NUMBER(10);
);


CREATE TABLE EXAMRESULT(
	MARK_ACHIEVED NUMBER(10),
	STUDENT_ID FOREIGN KEY REFERENCES STUDENT(STUDENT_ID) NUMBER(10),
	EXAM_ID FOREIGN KEY REFERENCES EXAM(EXAM_ID) NUMBER(10);
);


CREATE TABLE LECTURER(
	LECTURER_ID NUMBER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	SUBJECT_ID FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID) NUMBER(10);
);


CREATE TABLE QUESTION(
	QUESTION_ID NUMBER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MAX_MARK NUMBER(10),
	AUTHOR VARCHAR(50),
	EXAM_ID FOREIGN KEY REFERENCES EXAM(EXAM_ID) NUMBER(10),
	LECTURER_ID FOREIGN KEY REFERENCES LECTURER(LECTURER_ID) NUMBER(10);
);

END;