SET TERMOUT ON
PROMPT Inserting new testing values into tables. Please stand by.
--SET TERMOUT OFF

INSERT INTO SUBJECT VALUES('Software Engingeering', 'Intro to the world of pain and work.', 1);
INSERT INTO SUBJECT VALUES('Internet Applications', 'Messes with your mind like nothing else.', 1);
INSERT INTO SUBJECT VALUES('SoftEng Project', 'PAIN. SO MUCH PAIN!', 2);
INSERT INTO SUBJECT VALUES('ISA', 'NOT ISIS', 2);


INSERT INTO STUDENT VALUES('Tommy', 'Gunn', 2, 1);
INSERT INTO STUDENT VALUES('Juan', 'Cena', 3, 2);
INSERT INTO STUDENT VALUES('Caesar', 'Rome', 1. 3);
INSERT INTO STUDENT VALUES('Sammy', 'Christian', 4, 4);


INSERT INTO TABLE COURSEWORK(1, 25);
INSERT INTO TABLE COURSEWORK(2, 50);
INSERT INTO TABLE COURSEWORK(3, 75);
INSERT INTO TABLE COURSEWORK(4, 100);


INSERT INTO COURSEWORKRESULT VALUES(25, 1, 1);
INSERT INTO COURSEWORKRESULT VALUES(44, 2, 2);
INSERT INTO COURSEWORKRESULT VALUES(63, 3, 3);
INSERT INTO COURSEWORKRESULT VALUES(41, 4, 4);


INSERT INTO EXAM VALUES(40, 'no', 1);
INSERT INTO EXAM VALUES(50, 'no', 2);
INSERT INTO EXAM VALUES(100, 'yes', 3);
INSERT INTO EXAM VALUES(200, 'no', 4);


INSERT INTO EXAMRESULT VALUES(40, 1, 1);
INSERT INTO EXAMRESULT VALUES(44, 2, 2);
INSERT INTO EXAMRESULT VALUES(90, 3, 3);
INSERT INTO EXAMRESULT VALUES(53, 4, 4);


SET TERMOUT OFF
PROMPT Finished inserting new values. Please proceed with testing.
