SET TERMOUT ON
PROMPT Inserting new testing values into tables. Please stand by.
--SET TERMOUT OFF

INSERT INTO SUBJECT VALUES(0, 'Software Engineering', 'Intro to the world of pain and work.', 1);
INSERT INTO SUBJECT VALUES(1, 'Internet Applications', 'Messes with your mind like nothing else.', 1);
INSERT INTO SUBJECT VALUES(2, 'SoftEng Project', 'PAIN. SO MUCH PAIN!', 2);
INSERT INTO SUBJECT VALUES(3, 'ISA', 'NOT ISIS', 2);


INSERT INTO STUDENT VALUES(0, 'Tommy', 'Gunn', 2, 1);
INSERT INTO STUDENT VALUES(1, 'Juan', 'Cena', 3, 2);
INSERT INTO STUDENT VALUES(2, 'Caesar', 'Rome', 1, 3);
INSERT INTO STUDENT VALUES(3, 'Sammy', 'Christian', 4, 4);


INSERT INTO TABLE COURSEWORK(0, 0, 25);
INSERT INTO TABLE COURSEWORK(1, 1, 50);
INSERT INTO TABLE COURSEWORK(2, 2, 75);
INSERT INTO TABLE COURSEWORK(3, 3, 100);


INSERT INTO COURSEWORKRESULT VALUES(25, 0, 0);
INSERT INTO COURSEWORKRESULT VALUES(44, 1, 1);
INSERT INTO COURSEWORKRESULT VALUES(63, 2, 2);
INSERT INTO COURSEWORKRESULT VALUES(41, 3, 3);


INSERT INTO LECTURER VALUES(0, "Prof", "Nikola", "Tesla", 0, 0);
INSERT INTO LECTURER VALUES(1, "Dr", "Sameen", "Hindu", 1, 1);
INSERT INTO LECTURER VALUES(2, "Mr", "Cesar", "Tarukiyanium", 2, 2);
INSERT INTO LECTURER VALUES(3, "Mrs", "Anabelle", "Smithy m8", 3, 3);


INSERT INTO EXAM VALUES(0, 40, 'no', 0);
INSERT INTO EXAM VALUES(1, 50, 'no', 1);
INSERT INTO EXAM VALUES(2, 100, 'yes', 2);
INSERT INTO EXAM VALUES(3, 200, 'no', 3);


INSERT INTO EXAMRESULT VALUES(40, 0, 0);
INSERT INTO EXAMRESULT VALUES(44, 1, 1);
INSERT INTO EXAMRESULT VALUES(90, 2, 2);
INSERT INTO EXAMRESULT VALUES(53, 3, 3);


INSERT INTO QUESTION VALUES(0, 5, "Prof. Tesla", 0, 0);
INSERT INTO QUESTION VALUES(1, 5, "Dr Hindu", 1, 1);
INSERT INTO QUESTION VALUES(2, 5, "Mr Tarukiyanium", 2, 2);
INSERT INTO QUESTION VALUES(3, 5, "Mrs Smithy m8", 3, 3);


SET TERMOUT OFF
PROMPT Finished inserting new values. Please proceed with testing.
