SELECT SUBJECT.NAME AS SubjectName,
MAX(EXAMRESULT.MARK_ACHIEVED) AS Highest, MIN(EXAMRESULT.MARK_ACHIEVED) AS Lowest,  
FROM SUBJECT, EXAM, EXAMRESULT
WHERE EXAM.EXAM_ID = EXAMRESULT.EXAM_ID 
AND SUBJECT.SUBJECT_ID = EXAM.SUBJECT_ID
GROUP BY SUBJECT.NAME;