/* Select all students who got a exam mark >= 80% for their subjects */
SELECT SUBJECT.NAME AS Subject, STUDENT.FIRST_NAME || ' ' || STUDENT.LAST_NAME AS Name, EXAMRESULT.MARK_ACHIEVED AS Mark, EXAM.TOTAL_MARK AS TotalMark
FROM STUDENT
INNER JOIN EXAMRESULT ON EXAMRESULT.STUDENT_ID = STUDENT.STUDENT_ID 
INNER JOIN EXAM ON EXAM.EXAM_ID = EXAMRESULT.EXAM_ID
INNER JOIN SUBJECT ON SUBJECT.SUBJECT_ID = EXAM.SUBJECT_ID
WHERE ((EXAMRESULT.MARK_ACHIEVED / EXAM.TOTAL_MARK)*100) >= 80;