 /* Students who got 70% or more for their coursework */
SELECT SUBJECT.NAME AS Subject, STUDENT.FIRST_NAME || ' ' || STUDENT.LAST_NAME AS Name, COURSEWORKRESULT.MARK_ACHIEVED AS CourseworkMark, COURSEWORK.MAX_MARK AS TotalMark
FROM STUDENT
INNER JOIN COURSEWORKRESULT ON COURSEWORKRESULT.STUDENT_ID = STUDENT.STUDENT_ID
INNER JOIN COURSEWORK ON COURSEWORK.COURSEWORK_ID = COURSEWORKRESULT.COURSEWORK_ID 
INNER JOIN SUBJECT ON SUBJECT.SUBJECT_ID = COURSEWORK.SUBJECT_ID
WHERE ((COURSEWORKRESULT.MARK_ACHIEVED / COURSEWORK.MAX_MARK)*100) >= 70;