/*  Students who passed a 'Software Engineering' exam */
CREATE VIEW PASSED_SE_EXAM AS
	SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME 
	FROM STUDENT, EXAM, EXAMRESULT, SUBJECT
	WHERE STUDENT.STUDENT_ID = EXAMRESULT.STUDENT_ID 
	AND EXAM.SUBJECT_ID = SUBJECT.SUBJECT_ID ANDSUBJECT.NAME='Software Engineering'
	AND EXAMRESULT.MARK_ACHIEVED > 40;
