CREATE VIEW YR2_STUDENTS AS 
		SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME
		FROM STUDENT
		WHERE STUDENT.YEAR = '2';
		
		
CREATE VIEW MH_LECTURER AS
		SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME
		FROM STUDENT, LECTURER
		WHERE STUDENT.SUBJECT_ID = LECTURER.SUBJECT_ID 
		AND LECTURER.FIRST_NAME = 'Andrew'
		AND LECTURER.LAST_NAME = 'Smith';

CREATE VIEW PASSED_OOP_EXAM AS
		SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME 
		FROM  STUDENT, EXAM, EXAMRESULT
		WHERE STUDENT.STUDENT_ID = EXAMRESULT.STUDENT_ID
		AND EXAM.SUBJECT_ID = 2
		AND EXAMRESULT.MARK_ACHIEVED > 40;