CREATE VIEW PASSED_OOP_EXAM AS
		SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME 
		FROM  STUDENT, EXAM, EXAMRESULT
		WHERE STUDENT.STUDENT_ID = EXAMRESULT.STUDENT_ID
		AND EXAM.SUBJECT_ID = 2
		AND EXAMRESULT.MARK_ACHIEVED > 40;