CREATE VIEW MH_LECTURER AS
		SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME
		FROM STUDENT, LECTURER
		WHERE STUDENT.SUBJECT_ID = LECTURER.SUBJECT_ID 
		AND LECTURER.FIRST_NAME = 'Andrew'
		AND LECTURER.LAST_NAME = 'Smith';