CREATE VIEW PASSED_OOP_EXAM -- Students that passed OOP exam
AS
SELECT STUDENT.FIRST_NAME, STUDENT.LAST_NAME, 
FROM  STUDENT,
WHERE STUDENT.STUDENT_ID = EXAMRESULT.STUDENT_ID
AND EXAM.SUBJECT_ID = 2
AND EXAMRESULT.MARK_ACHIEVED > 40;